version: '3.8'

services:
  contract-manatement:
    build:
      context: ./
    restart: unless-stopped
    volumes:
      - ./src:/opt/app-root/contracts-manager/src
    ports:
      - 3000:3000
      - 8000:8000
