openapi: 3.0.0
info:
  title: Contract management
  version: '0.1'
servers:
  - url: http://127.0.0.1:3000/dev
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: >-
        `Bearer: ` prefix, e.g. "Bearer ab34nc34v34".
tags:
  - name: user
  - name: contract
paths:
  /create-user:
    post:
      tags:
        - user
      summary: create user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: 'test'
                password: 'test'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /login-user:
    post:
      tags:
        - user
      summary: login user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: 'test'
                password:
                  type: string
                  example: 'test'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /create-contract:
    post:
      tags:
        - contract
      summary: create contract
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                contractName:
                  type: string
                  example: testContract
                templateId:
                  type: string
                  format: uuid
                  example: af7c1fe6-d669-414e-b066-e9733f0de7a8
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /get-contract:
    get:
      tags:
        - contract
      summary: get a particular contract of the user
      parameters:
        - name: id
          in: query
          description: ID of contract to fetch
          required: true
          schema:
            type: string
            format: uuid
            example: af7c1fe6-d669-414e-b066-e9733f0de7a8
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /get-contract-ids:
    get:
      tags:
        - contract
      summary: get contract ids of the user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
